name: Tests
run-name: Tests

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  tests:
    runs-on: 'ubuntu-latest'
    steps:
      jobs:
        test:
          runs-on: ubuntu-latest
          steps:
            - uses: actions/checkout@v2
            - run: |
                npm install
            - run: |
                npm run test
